numpy-
numpy is numerical python
it is used for-

fast mathematical operations
working with large dataset
scientific computing


In [2]:
import numpy as np


python list is numpy array

numbers=[1,2,3,4]
data=[1,"hello",3.5]

- can store different datatypes
- stored in scattered memory
- slower for larger calculations


numpy array:
arr=np.array([1,2,3,4])

- stores same datatype
- stored in continuous memory
- much faster
- supports mathematical operations

memory difference-
python list                                 numpy array
-------------                              -----------------    
- flexible                                 - fixed data type         
- slower                                   - faster 
- different types allowed                  - same type only
- memory scattered                         - memory is continuous 

In [10]:
#ndarray- (N-dimensional array)
arr=np.array([1,2,3,4])
print(arr * 2)

#normal list
numbers=[1,2,3,4]
print(numbers * 2)

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
#converting list to array
arr=np.array([10,20,30,40])
print(arr)

#2D example
arr1=np.array([[1,2,3],
              [4,5,6]])
              
print(arr1)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
#np.zeros
#creates arrays filled with zeros
arr=np.zeros(5)
print(arr)

#array with 2 rows,3 columns of zeros
arr1=np.zeros((2,3))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#np.arange
#similar to range function
np.arange(0,10,2)
#start,stop,step

array([0, 2, 4, 6, 8])

In [ ]:
#np.linspace
#creates evenly spaced numbers
print(np.linspace(0,10,5))

print(np.logspace(1,3,5))   #creates evenly spaced log values
#(start,stop,num_of_values)

[ 0.   2.5  5.   7.5 10. ]
[  10.           31.6227766   100.          316.22776602 1000.        ]


In [ ]:
#np.ones
#creates arrays filled with ones
arr=np.ones(5)
print(arr)
np.ones((2,3))  #2rows,3 columns of ones
#use when you need default values of 1


[1. 1. 1. 1. 1.]


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#np.full
#creates arrays filled with specified value
arr=np.full(5,7)    #one dimensional
print(arr)
np.full((2,3),7)#2rows,3 columns of 7
#(shape,fill_value,[dtype])   here dtype is optional
#ueful for initialization with specific value

print(np.full((3,3),5,dtype=float))
print(np.full((3,2),"NA"))  #used when marking missing categorial values
print(np.full((3,3),True))  #used for boolean arrays

[7 7 7 7 7]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[['NA' 'NA']
 ['NA' 'NA']
 ['NA' 'NA']]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#np.eye
#creates identity matrix(diagonal=1)
np.eye(3)
print(np.eye(4))



print(np.diag([1,2,3])) #creates a diagonal matrix with the given values on the diagonal

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [19]:
#if all 5 students get a bonus marks of 2
marks=np.array([80,85,90,95,97])
bonus=np.full(marks.shape,2)  #create an array of 2s with the same shape as marks
final_marks=marks+bonus
print(final_marks)

[82 87 92 97 99]


In [29]:
#np.random
#creates an array of random numbers between 0 and 1
print(np.random.rand(5))  #1D array of 5 random numbers
print(np.random.rand(2,3))  #2D array of random numbers with 2 rows and 3 columns

print(np.random.randint(1,10,5))  #5 random integers between 1 and 9 (10 is exclusive)

#random choice
colors=["red","blue","green"]
print(np.random.choice(colors))

#multiple selections
print(np.random.choice(colors,size=5)) 


[0.86982888 0.41589912 0.28629918 0.97607163 0.12761956]
[[0.40996327 0.72232272 0.35076187]
 [0.99668714 0.14951396 0.97507195]]
[3 4 1 2 9]
green
['green' 'blue' 'green' 'red' 'green']


broadcasting
#allows operations on arrays of different shapes

#broadcasting rules:
two arrays are compatible if
1. they have same shape
    or
2. one of them is 1
    or
3. smaller array can stretch into match larger    


In [35]:
arr=np.array([1,2,3,4,5])
print(arr+5)

[ 6  7  8  9 10]


In [36]:
#broadcasting 1d with 2d

arr1=np.array([[1,2,3],
              [4,5,6]])
arr2=np.array([10,20,30])
print(arr1+arr2)

[[11 22 33]
 [14 25 36]]


In [ ]:
a=np.array(([1,2,3],
         [4,5,6]))

b=np.array(([1,2]))
print(a+b)   #broadcasting fails

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [41]:
#column broadcasting
arr=np.array(([1,2,3],
         [4,5,6]))
col=np.array([[10],
              [20]])
print(arr+col)

[[11 12 13]
 [24 25 26]]


#vectorization
#doing operations on entire arrays at once without once insted of using loops

vectorization makes it:
- faster
- cleaner mode
- less memory usage


In [43]:
#square all numbers
arr=np.array([1,2,3,4])
print(arr**2)

[ 1  4  9 16]


In [44]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [47]:
#conditional vectorization
arr=np.array([10,20,30,40])
print(arr>25)

[False False  True  True]


In [ ]:
#using condition to modify values
arr[arr>25]=100     #wich is greater than 25 will be replaced by 100
print(arr)

[ 10  20 100 100]


In [ ]:
#using where
np.where(arr>25,1,0)   #if condition is true replace with 1 else keep original value(kepps in 0)


array([0, 0, 1, 1])

In [54]:
#mathematical operations
arr1=np.array([1,2,3,4])
print(np.sort(arr1))
print(np.sqrt(arr1))
print(np.log(arr1))
print(np.sin(arr1))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
#broadcasting +vectorization together
arr=np.array([[1,2,3],
            [4,5,6]])
mean=np.array([2,3,4])
print(arr-mean)
#broadcasting handles shape,vecrorization handles elementwise operations    

[[-1 -1 -1]
 [ 2  2  2]]
